name: 'deploy-production'

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  production-deploy-base:
    name: 'deploy-production-base'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: infrastructure/components/base

    steps:
      - name: Git clone the rpository
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.AWS_MANAGEMENT_ROLE }}"
          aws-region: us-east-1

      - name: Setup latest Terraform version
        uses: hashicorp/setup-terraform@v2

      - name: Setup Terraform variables
        run: |-
          cat <<EOT > terraform.tfvars
          accounts = { "${{ secrets.AWS_ACCOUNTS }}" }
          EOT

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend-config="key=base/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file="../../environments/base.tfvars"
