name: "deploy-staging"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  staging-deploy-frontend:
    name: "deploy-staging-frontend"
    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run:
        shell: bash
        working-directory: infrastructure/components/frontend

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "${{ secrets.AWS_MANAGEMENT_ROLE }}"
          aws-region: us-east-1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend-config="key=stage-frontend/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file="../../environments/stage.tfvars" -var="role_arn=${{ secrets.AWS_GITHUB_ACTIONS_ROLE}}"
